"""
## demo_context_assembly

**Pillar 1: Context Assembly** — Enriching structured data with LLM context
for downstream AI agents.

```
Raw Data (warehouse) → @task.llm enrichment per record → Cross-record summary → Downstream agent
```

**Why Astro is essential here:**
- LLMs need fresh, structured context — Airflow schedules, retries, and audits every step
- `expand()` fans out N enrichment calls in parallel with zero boilerplate
- Full lineage in Astro Observe: know exactly what data fed each model call

**Mock mode:** set `MOCK_LLM=true` in `.env` to run end-to-end with no API key.
Rule-based responses simulate realistic LLM outputs from the position data.
Set `MOCK_LLM=false` and add an API key to switch to real model calls with no
other code changes.

Customers: aampe · Notion · Red Hat
"""

from __future__ import annotations

import os
from datetime import datetime, timezone
from typing import Literal

from pydantic import BaseModel, Field

from airflow.sdk import dag, task

MOCK_LLM = os.getenv("MOCK_LLM", "false").lower() == "true"


# ---------------------------------------------------------------------------
# Pydantic output models
# ---------------------------------------------------------------------------

class AssetContext(BaseModel):
    """Risk context assembled by the LLM for a single portfolio position."""

    ticker: str = Field(description="Ticker symbol for this asset (e.g. AAPL, NVDA)")
    summary: str = Field(description="1-2 sentence summary of the position")
    risk_level: Literal["LOW", "MEDIUM", "HIGH", "CRITICAL"] = Field(
        description="Risk classification based on volatility, news, and P&L"
    )
    key_factors: list[str] = Field(
        description="Top 3 factors driving the risk assessment",
        min_length=1,
        max_length=3,
    )
    context_for_agent: str = Field(
        description=(
            "Compact, information-dense string ready for injection into a "
            "downstream AI agent prompt or embedding pipeline"
        )
    )
    recommended_action: Literal["HOLD", "REVIEW", "ESCALATE"] = Field(
        description="Recommended next action for the portfolio management agent"
    )


class PortfolioSummary(BaseModel):
    """Cross-asset portfolio summary generated by the LLM."""

    overall_risk: Literal["LOW", "MEDIUM", "HIGH", "CRITICAL"]
    narrative: str = Field(description="2-3 sentence portfolio-level narrative")
    top_concern: str = Field(description="Single most important risk to flag")
    assets_requiring_review: list[str] = Field(
        description="Ticker symbols that need human or agent attention"
    )


# ---------------------------------------------------------------------------
# Mock helpers — rule-based responses used when MOCK_LLM=true
# ---------------------------------------------------------------------------

_RISK_ORDER = ["LOW", "MEDIUM", "HIGH", "CRITICAL"]


def _mock_asset_context(position: dict) -> dict:
    pnl_pct = (position["current_price"] - position["avg_cost"]) / position["avg_cost"] * 100
    vol = position["volatility_30d"]
    ticker = position["ticker"]

    risk_level: Literal["LOW", "MEDIUM", "HIGH", "CRITICAL"]
    if vol >= 0.35:
        risk_level = "CRITICAL"
    elif vol >= 0.25:
        risk_level = "HIGH"
    elif vol >= 0.15:
        risk_level = "MEDIUM"
    else:
        risk_level = "LOW"

    action: Literal["HOLD", "REVIEW", "ESCALATE"]
    if risk_level in ("CRITICAL", "HIGH") or pnl_pct < -5:
        action = "ESCALATE" if risk_level == "CRITICAL" else "REVIEW"
    else:
        action = "HOLD"

    return AssetContext(
        ticker=ticker,
        summary=(
            f"{ticker} is {'outperforming' if pnl_pct > 10 else 'underperforming' if pnl_pct < 0 else 'in line'} "
            f"with {pnl_pct:+.1f}% P&L and {vol:.0%} 30-day volatility in the {position['sector']} sector."
        ),
        risk_level=risk_level,
        key_factors=position["recent_news"][:3],
        context_for_agent=(
            f"{ticker}: sector={position['sector']}, pnl={pnl_pct:+.1f}%, "
            f"vol={vol:.0%}, risk={risk_level}, action={action}"
        ),
        recommended_action=action,
    ).model_dump()


def _mock_portfolio_summary(asset_contexts: list[dict]) -> dict:
    """Aggregate per-asset risk into a portfolio-level narrative — derived from data."""
    risks = [c.get("risk_level", "MEDIUM") for c in asset_contexts]
    highest = max(risks, key=lambda r: _RISK_ORDER.index(r)) if risks else "LOW"
    for_review = [c["ticker"] for c in asset_contexts if c.get("recommended_action") != "HOLD"]
    n_elevated = sum(1 for r in risks if r in ("HIGH", "CRITICAL"))

    # Highest-risk asset drives the top_concern; ties broken by appearance order
    top_asset = max(
        asset_contexts,
        key=lambda c: _RISK_ORDER.index(c.get("risk_level", "LOW")),
        default=None,
    )
    if top_asset is not None and top_asset.get("risk_level") in ("HIGH", "CRITICAL"):
        top_concern = (
            f"{top_asset['ticker']} ({top_asset['risk_level'].lower()} risk): "
            f"{top_asset.get('summary', '').rstrip('.')}."
        )
    else:
        top_concern = "No single position presents a critical risk; monitor aggregate exposure."

    if n_elevated:
        narrative = (
            f"Portfolio of {len(asset_contexts)} positions shows {highest.lower()} aggregate risk. "
            f"{n_elevated} position(s) flagged for elevated volatility or adverse news flow."
        )
    else:
        narrative = (
            f"Portfolio of {len(asset_contexts)} positions is stable; "
            f"all positions show low-to-moderate risk profiles."
        )

    return PortfolioSummary(
        overall_risk=highest,
        narrative=narrative,
        top_concern=top_concern,
        assets_requiring_review=for_review,
    ).model_dump()


# ---------------------------------------------------------------------------
# DAG
# ---------------------------------------------------------------------------

@dag(
    dag_id="demo_context_assembly",
    description="[DEMO] Pillar 1: Context Assembly — LLM-enriched financial data for downstream AI agents",
    start_date=datetime(2026, 1, 1),
    schedule=None,
    catchup=False,
    tags=["demo", "ai", "context-assembly", "pillar-1"],
    doc_md=__doc__,
)
def demo_context_assembly():

    @task
    def extract_portfolio_positions() -> list[dict]:
        """Pull portfolio positions from the data warehouse.

        In production: swap for SnowflakeHook, BigQueryHook, or an S3 sensor.
        """
        print(f"[{'MOCK_LLM=true — rule-based mock responses' if MOCK_LLM else 'MOCK_LLM=false — live pydanticai LLM calls'}]")
        return [
            {
                "ticker": "AAPL",
                "position_usd": 2_400_000,
                "avg_cost": 182.50,
                "current_price": 211.20,
                "sector": "Technology",
                "volatility_30d": 0.18,
                "recent_news": [
                    "Q2 earnings beat expectations by 8%",
                    "Vision Pro sales below analyst forecast",
                    "Services revenue hits all-time high",
                ],
            },
            {
                "ticker": "JPM",
                "position_usd": 900_000,
                "avg_cost": 198.00,
                "current_price": 224.80,
                "sector": "Financial Services",
                "volatility_30d": 0.22,
                "recent_news": [
                    "Fed rate decision pending — market expects 25bps cut",
                    "Credit loss provisions increased 12% QoQ",
                    "Investment banking revenue up 40% YoY",
                ],
            },
            {
                "ticker": "NVDA",
                "position_usd": 3_750_000,
                "avg_cost": 495.00,
                "current_price": 875.40,
                "sector": "Semiconductors",
                "volatility_30d": 0.38,
                "recent_news": [
                    "Blackwell GPU demand significantly exceeds supply",
                    "New export restrictions to China announced",
                    "Data center revenue up 427% YoY",
                ],
            },
            {
                "ticker": "BRK.B",
                "position_usd": 1_100_000,
                "avg_cost": 355.00,
                "current_price": 412.30,
                "sector": "Conglomerate / Insurance",
                "volatility_30d": 0.11,
                "recent_news": [
                    "Cash reserves at record $168B",
                    "Berkshire reduced Apple stake by 50%",
                    "Insurance underwriting profit up 18%",
                ],
            },
        ]

    # ------------------------------------------------------------------
    # @task.llm: enrich each position with LLM risk context (parallel)
    # ------------------------------------------------------------------
    if MOCK_LLM:
        @task
        def assemble_asset_context(position: dict) -> dict:
            """Mock: rule-based risk context from position data."""
            return _mock_asset_context(position)
    else:
        @task.llm(
            llm_conn_id="pydanticai_default",
            output_type=AssetContext,
            system_prompt=(
                "You are a quantitative risk analyst at a hedge fund. "
                "Given a portfolio position, produce a structured risk context object "
                "that downstream AI agents will use for portfolio management decisions. "
                "Be precise and data-driven. The context_for_agent field should be compact "
                "and information-dense — suitable for direct injection into another model's prompt."
            ),
        )
        def assemble_asset_context(position: dict) -> str:
            """Build the LLM prompt for a single portfolio position."""
            pnl_pct = (
                (position["current_price"] - position["avg_cost"]) / position["avg_cost"] * 100
            )
            return (
                f"Ticker: {position['ticker']} | Sector: {position['sector']}\n"
                f"Position: ${position['position_usd']:,} | P&L: {pnl_pct:+.1f}% | "
                f"30d Volatility: {position['volatility_30d']:.0%}\n"
                f"Recent News:\n"
                + "\n".join(f"  - {n}" for n in position["recent_news"])
                + "\n\nGenerate a structured risk context for this position."
            )

    # ------------------------------------------------------------------
    # @task.llm: cross-asset portfolio summary (second LLM pass)
    # ------------------------------------------------------------------
    if MOCK_LLM:
        @task
        def generate_portfolio_summary(asset_contexts: list[dict]) -> dict:
            """Mock: aggregate asset contexts into a portfolio summary."""
            return _mock_portfolio_summary(asset_contexts)
    else:
        @task.llm(
            llm_conn_id="pydanticai_default",
            output_type=PortfolioSummary,
            system_prompt=(
                "You are a senior portfolio risk officer. "
                "Given individual asset risk assessments, generate a portfolio-level summary "
                "that highlights the most critical risks and actions required. "
                "This summary feeds the portfolio management AI agent."
            ),
        )
        def generate_portfolio_summary(asset_contexts: list[dict]) -> str:
            """Build a cross-asset portfolio summary prompt from individual asset contexts."""
            lines = ["Portfolio Risk Assessment — Cross-Asset Summary", "=" * 50, ""]
            for ctx in asset_contexts:
                lines.append(
                    f"{ctx.get('ticker', '?'):6s} [{ctx.get('risk_level', '?'):8s}] "
                    f"→ {ctx.get('recommended_action', '?')}: {ctx.get('summary', '')}"
                )
            lines.append(
                "\nGenerate a portfolio-level risk narrative and flag assets requiring review."
            )
            return "\n".join(lines)

    # ------------------------------------------------------------------
    # Deliver enriched context to downstream systems
    # ------------------------------------------------------------------
    @task
    def deliver_context_to_downstream(
        positions: list[dict],
        asset_contexts: list[AssetContext | dict],
        portfolio_summary: PortfolioSummary | dict,
    ) -> dict:
        """Package enriched context and deliver to downstream systems.

        In production: write to a vector store (Pinecone, pgvector), Snowflake,
        a Kafka topic, or an API endpoint for real-time inference.
        Airflow guarantees this task only runs after all LLM enrichment completes.
        """
        contexts = [
            AssetContext.model_validate(c) if isinstance(c, dict) else c
            for c in asset_contexts
        ]
        if isinstance(portfolio_summary, dict):
            portfolio_summary = PortfolioSummary.model_validate(portfolio_summary)

        print("\n" + "=" * 60)
        print("CONTEXT ASSEMBLY COMPLETE")
        print("=" * 60)
        print(f"\nPortfolio Risk: {portfolio_summary.overall_risk}")
        print(f"Narrative:      {portfolio_summary.narrative}")
        print(f"Top Concern:    {portfolio_summary.top_concern}")
        print(f"Review Needed:  {', '.join(portfolio_summary.assets_requiring_review)}")
        print("\nPer-Asset Context:")
        for ctx in contexts:
            print(f"  {ctx.ticker:6s}  [{ctx.risk_level:8s}]  → {ctx.recommended_action}")

        return {
            "assembled_at": datetime.now(timezone.utc).isoformat(),
            "mock_mode": MOCK_LLM,
            "portfolio_risk": portfolio_summary.overall_risk,
            "assets_for_review": portfolio_summary.assets_requiring_review,
            "asset_contexts": [
                {
                    "ticker": ctx.ticker,
                    "risk_level": ctx.risk_level,
                    "action": ctx.recommended_action,
                    "agent_context": ctx.context_for_agent,
                }
                for ctx in contexts
            ],
            "ready_for_inference": True,
        }

    positions = extract_portfolio_positions()
    asset_contexts = assemble_asset_context.expand(position=positions)
    summary = generate_portfolio_summary(asset_contexts=asset_contexts)
    deliver_context_to_downstream(
        positions=positions,
        asset_contexts=asset_contexts,
        portfolio_summary=summary,
    )


demo_context_assembly()
